import { DrainageSegment } from './types';

// Reconstructed Synthetic Drainage Segments (Dashed Sky/Teal line)
// Generated by terrain flow direction, flow accumulation, and urban road constraints.
// Labelled clearly as DEMO / CANDIDATE RECONSTRUCTION.
export const reconstructedDrainageSegments: DrainageSegment[] = [
  {
    id: 'SYN-DR-001',
    name: 'Candidate Flow Link: Senapati Bapat Ridge to FC Trunk',
    type: 'reconstructed',
    coordinates: [[18.5320, 73.8290], [18.5290, 73.8412]],
    lengthMeters: 620,
    slopePercent: 2.3,
    catchmentAreaHa: 4.8,
    diameterMm: 800,
    confidence: 'HIGH',
    validationStatus: 'validated',
    evidence: [
      { id: 'ev-1', label: 'Terrain flow alignment', supported: true, notes: 'Direct downhill gradient along natural valley profile (DEM slope 2.3%)' },
      { id: 'ev-2', label: 'Road corridor agreement', supported: true, notes: 'Follows public street right-of-way' },
      { id: 'ev-3', label: 'Downstream connection', supported: true, notes: 'Discharges directly into verified Junction J-03 on FC Road' },
      { id: 'ev-4', label: 'Municipal record match', supported: false, notes: 'No physical surveyed CAD drawing in 2021 database' }
    ],
    recommendation: 'High confidence candidate. Field ground-truth with physical inspection chamber locate.',
    statusNotes: 'Candidate conduit inferred from DEM & road network'
  },
  {
    id: 'SYN-DR-002',
    name: 'Candidate Cross-Connector: Ghole Rd Terminal to JM Rd Trunk',
    type: 'reconstructed',
    coordinates: [[18.5315, 73.8445], [18.5300, 73.8465]],
    lengthMeters: 260,
    slopePercent: 1.4,
    catchmentAreaHa: 3.1,
    diameterMm: 750,
    confidence: 'HIGH',
    validationStatus: 'validated',
    evidence: [
      { id: 'ev-1', label: 'Terrain flow alignment', supported: true, notes: 'Continuous slope toward river axis' },
      { id: 'ev-2', label: 'Road corridor agreement', supported: true, notes: 'Aligned with cross-street connecting Ghole Rd to JM Rd' },
      { id: 'ev-3', label: 'Downstream connection', supported: true, notes: 'Connects known dead-end node J-13 to J-08' },
      { id: 'ev-4', label: 'Historical ponding relief', supported: true, notes: 'Eliminates structural network discontinuity' }
    ],
    recommendation: 'Strong candidate for hydraulic continuity. Field CCTV inspection advised.',
    statusNotes: 'Restores hydraulic connectivity for dead-end lateral'
  },
  {
    id: 'SYN-DR-003',
    name: 'Candidate Overland Flow Link: Model Colony Western Swale',
    type: 'reconstructed',
    coordinates: [[18.5345, 73.8335], [18.5350, 73.8350]],
    lengthMeters: 195,
    slopePercent: 2.8,
    catchmentAreaHa: 2.4,
    diameterMm: 600,
    confidence: 'HIGH',
    validationStatus: 'validated',
    evidence: [
      { id: 'ev-1', label: 'Terrain flow alignment', supported: true, notes: 'Steep hill runoff following natural drainage swale' },
      { id: 'ev-2', label: 'Road corridor agreement', supported: true, notes: 'Located under service lane pavement' },
      { id: 'ev-3', label: 'Downstream connection', supported: true, notes: 'Ties into verified inlet J-15' }
    ],
    recommendation: 'Validated flow corridor. Invert depth verification required.',
    statusNotes: 'Reconstructed upstream tributary'
  },
  {
    id: 'SYN-DR-004',
    name: 'Candidate Interceptor Branch: Deccan North Commercial Lane',
    type: 'reconstructed',
    coordinates: [[18.5220, 73.8390], [18.5245, 73.8398]],
    lengthMeters: 310,
    slopePercent: 1.7,
    catchmentAreaHa: 2.9,
    diameterMm: 600,
    confidence: 'HIGH',
    validationStatus: 'validated',
    evidence: [
      { id: 'ev-1', label: 'Terrain flow alignment', supported: true, notes: 'Consistent 1.7% fall toward FC Road' },
      { id: 'ev-2', label: 'Road corridor agreement', supported: true, notes: 'Follows dense commercial retail alleyway' },
      { id: 'ev-3', label: 'Downstream connection', supported: true, notes: 'Feeds into Junction J-02' }
    ],
    recommendation: 'Plausible stormwater lateral. Verify utility clutter (telecom / water lines).',
    statusNotes: 'Candidate commercial feeder'
  },
  {
    id: 'SYN-DR-005',
    name: 'Candidate Collector: Ferguson Hill South Catchment',
    type: 'reconstructed',
    coordinates: [[18.5195, 73.8310], [18.5180, 73.8360]],
    lengthMeters: 540,
    slopePercent: 3.4,
    catchmentAreaHa: 5.1,
    diameterMm: 750,
    confidence: 'HIGH',
    validationStatus: 'validated',
    evidence: [
      { id: 'ev-1', label: 'Terrain flow alignment', supported: true, notes: 'Prominent hill slope runoff path' },
      { id: 'ev-2', label: 'Road corridor agreement', supported: true, notes: 'Adjacent to arterial boundary' },
      { id: 'ev-3', label: 'Downstream connection', supported: true, notes: 'Discharges at Junction J-10' }
    ],
    recommendation: 'Candidate nallah feeder. Verify culvert crossing structure.',
    statusNotes: 'Candidate hill slope conduit'
  },
  {
    id: 'SYN-DR-006',
    name: 'Candidate Branch: Model Colony South to FC Trunk',
    type: 'reconstructed',
    coordinates: [[18.5325, 73.8375], [18.5340, 73.8428]],
    lengthMeters: 480,
    slopePercent: 1.9,
    catchmentAreaHa: 4.2,
    diameterMm: 700,
    confidence: 'MEDIUM',
    validationStatus: 'partially_validated',
    evidence: [
      { id: 'ev-1', label: 'Terrain flow alignment', supported: true, notes: 'Terrain contours direct flow southeast' },
      { id: 'ev-2', label: 'Road corridor agreement', supported: true, notes: 'Follows local residential lane' },
      { id: 'ev-3', label: 'Downstream connection', supported: true, notes: 'Discharges to J-04' },
      { id: 'ev-4', label: 'Building footprint interference', supported: false, notes: 'Passes near private property compound walls' }
    ],
    recommendation: 'Partially validated. Requires ground survey to check for private property encroachments.',
    statusNotes: 'Reconstructed pathway intersecting dense private plots'
  },
  {
    id: 'SYN-DR-007',
    name: 'Candidate Link: Prabhat Lane to Goodluck Chowk',
    type: 'reconstructed',
    coordinates: [[18.5200, 73.8360], [18.5245, 73.8398]],
    lengthMeters: 485,
    slopePercent: 1.5,
    catchmentAreaHa: 3.8,
    diameterMm: 600,
    confidence: 'MEDIUM',
    validationStatus: 'partially_validated',
    evidence: [
      { id: 'ev-1', label: 'Terrain flow alignment', supported: true, notes: 'Favorable natural gravity slope' },
      { id: 'ev-2', label: 'Road corridor agreement', supported: true, notes: 'Follows secondary road' },
      { id: 'ev-3', label: 'Downstream connection', supported: true, notes: 'Terminates at verified Junction J-02' },
      { id: 'ev-4', label: 'Invert level mismatch risk', supported: false, notes: 'Elevation differential at junction requires physical confirmation' }
    ],
    recommendation: 'Partially validated. Level survey needed at J-02 manhole.',
    statusNotes: 'Candidate urban feeder'
  },
  {
    id: 'SYN-DR-008',
    name: 'Candidate Diagonal Link: Tukaram Paduka to Ghole Road',
    type: 'reconstructed',
    coordinates: [[18.5290, 73.8412], [18.5270, 73.8432]],
    lengthMeters: 330,
    slopePercent: 1.2,
    catchmentAreaHa: 2.7,
    diameterMm: 600,
    confidence: 'MEDIUM',
    validationStatus: 'partially_validated',
    evidence: [
      { id: 'ev-1', label: 'Terrain flow alignment', supported: true, notes: 'Consistent lateral gradient' },
      { id: 'ev-2', label: 'Road corridor agreement', supported: true, notes: 'Crosses through commercial diagonal street' },
      { id: 'ev-3', label: 'Downstream connection', supported: true, notes: 'Connects J-03 to J-12' }
    ],
    recommendation: 'Candidate relief line. Validate underground utility conflicts before assuming flow routing.',
    statusNotes: 'Candidate cross-basin relief link'
  },
  {
    id: 'SYN-DR-009',
    name: 'Candidate Branch: Shivajinagar Residential Sector B',
    type: 'reconstructed',
    coordinates: [[18.5365, 73.8390], [18.5385, 73.8440]],
    lengthMeters: 440,
    slopePercent: 1.6,
    catchmentAreaHa: 3.6,
    diameterMm: 700,
    confidence: 'MEDIUM',
    validationStatus: 'partially_validated',
    evidence: [
      { id: 'ev-1', label: 'Terrain flow alignment', supported: true, notes: 'Flow follows urban asphalt grade' },
      { id: 'ev-2', label: 'Road corridor agreement', supported: true, notes: 'Aligned with public street network' },
      { id: 'ev-3', label: 'Downstream connection', supported: true, notes: 'Connects to J-05' }
    ],
    recommendation: 'Medium confidence candidate. Inspect for sedimentation or partial collapse.',
    statusNotes: 'Candidate residential branch'
  },
  {
    id: 'SYN-DR-010',
    name: 'Candidate Collector: Deccan Gymkhana West Alley',
    type: 'reconstructed',
    coordinates: [[18.5160, 73.8380], [18.5205, 73.8385]],
    lengthMeters: 420,
    slopePercent: 1.8,
    catchmentAreaHa: 3.3,
    diameterMm: 600,
    confidence: 'MEDIUM',
    validationStatus: 'partially_validated',
    evidence: [
      { id: 'ev-1', label: 'Terrain flow alignment', supported: true, notes: 'Natural drainage course along parcel boundaries' },
      { id: 'ev-2', label: 'Downstream connection', supported: true, notes: 'Ties into J-01' },
      { id: 'ev-3', label: 'Road alignment', supported: false, notes: 'Traverses narrow non-vehicular pedestrian pathway' }
    ],
    recommendation: 'Partially validated. May be covered masonry drain rather than standard pipe.',
    statusNotes: 'Candidate pedestrian corridor drain'
  },
  {
    id: 'SYN-DR-011',
    name: 'Candidate Riverfront Feeder: Lakdi Pul West Pocket',
    type: 'reconstructed',
    coordinates: [[18.5190, 73.8445], [18.5185, 73.8480]],
    lengthMeters: 360,
    slopePercent: 1.3,
    catchmentAreaHa: 2.8,
    diameterMm: 600,
    confidence: 'MEDIUM',
    validationStatus: 'partially_validated',
    evidence: [
      { id: 'ev-1', label: 'Terrain flow alignment', supported: true, notes: 'Direct descent to river embankment' },
      { id: 'ev-2', label: 'Road corridor agreement', supported: true, notes: 'Follows river approach road' },
      { id: 'ev-3', label: 'Downstream connection', supported: true, notes: 'Connects to J-17' }
    ],
    recommendation: 'Medium confidence. Check backflow flap valve condition during river high-water.',
    statusNotes: 'Candidate riverfront feeder'
  },
  {
    id: 'SYN-DR-012',
    name: 'Candidate Infill: Sambhaji Park East Perimeter',
    type: 'reconstructed',
    coordinates: [[18.5260, 73.8425], [18.5255, 73.8452]],
    lengthMeters: 290,
    slopePercent: 1.0,
    catchmentAreaHa: 2.2,
    diameterMm: 600,
    confidence: 'MEDIUM',
    validationStatus: 'partially_validated',
    evidence: [
      { id: 'ev-1', label: 'Terrain flow alignment', supported: true, notes: 'Gentle fall across park boundary' },
      { id: 'ev-2', label: 'Downstream connection', supported: true, notes: 'Connects to J-07' },
      { id: 'ev-3', label: 'Municipal record match', supported: false, notes: 'Unrecorded park drainage channel' }
    ],
    recommendation: 'Verify if open swale or closed culvert.',
    statusNotes: 'Candidate park boundary collector'
  },
  {
    id: 'SYN-DR-013',
    name: 'Candidate Overland Flow: Ghole Rd Northeast Pocket',
    type: 'reconstructed',
    coordinates: [[18.5330, 73.8420], [18.5350, 73.8478]],
    lengthMeters: 550,
    slopePercent: 1.5,
    catchmentAreaHa: 4.0,
    diameterMm: 700,
    confidence: 'MEDIUM',
    validationStatus: 'partially_validated',
    evidence: [
      { id: 'ev-1', label: 'Terrain flow alignment', supported: true, notes: 'Direct downhill flow vector' },
      { id: 'ev-2', label: 'Downstream connection', supported: true, notes: 'Reaches outfall link J-09' },
      { id: 'ev-3', label: 'Urban barrier', supported: false, notes: 'High density mixed-use commercial blocks' }
    ],
    recommendation: 'Candidate flowpath. Urban density may force flow along street gutters instead of direct subsurface pipe.',
    statusNotes: 'Candidate urban collector'
  },
  {
    id: 'SYN-DR-014',
    name: 'Candidate Reconstructed Segment SYN-DR-014',
    type: 'reconstructed',
    coordinates: [[18.5280, 73.8360], [18.5290, 73.8412]],
    lengthMeters: 186,
    slopePercent: 1.8,
    catchmentAreaHa: 3.2,
    diameterMm: 700,
    confidence: 'MEDIUM',
    validationStatus: 'partially_validated',
    evidence: [
      { id: 'ev-1', label: 'Terrain flow alignment', supported: true, notes: 'DEM surface slope matches simulated flow path (1.8% fall)' },
      { id: 'ev-2', label: 'Road corridor agreement', supported: true, notes: 'Street center-line aligns with flow direction' },
      { id: 'ev-3', label: 'Downstream connection', supported: true, notes: 'Direct hydraulic link to confirmed Junction J-03 on FC Road' },
      { id: 'ev-4', label: 'Municipal infrastructure record', supported: false, notes: 'No physical surveyed CAD record in legacy municipal GIS' }
    ],
    recommendation: 'Requires verification before inclusion in baseline engineering design. Do not treat as confirmed physical pipe.',
    statusNotes: 'Candidate drainage pathway reconstructed from DEM flow-accumulation & road network'
  },
  {
    id: 'SYN-DR-015',
    name: 'Candidate Cross-Block Flowpath: Deccan East Pocket',
    type: 'reconstructed',
    coordinates: [[18.5225, 73.8465], [18.5230, 73.8505]],
    lengthMeters: 390,
    slopePercent: 0.5, // Low slope & low confidence
    catchmentAreaHa: 2.1,
    diameterMm: 500,
    confidence: 'LOW',
    validationStatus: 'requires_verification',
    isProblemSegment: true,
    problemType: 'low_slope',
    problemDescription: 'Very low slope (0.5%) and traverses across privately walled building compounds. High risk of flow obstruction.',
    evidence: [
      { id: 'ev-1', label: 'Terrain flow alignment', supported: true, notes: 'Weak natural slope (0.5%)' },
      { id: 'ev-2', label: 'Road corridor agreement', supported: false, notes: 'Cuts across private commercial property plots' },
      { id: 'ev-3', label: 'Downstream connection', supported: true, notes: 'Connects to J-18' },
      { id: 'ev-4', label: 'Structural continuity', supported: false, notes: 'Unlikely to have an uninterrupted subsurface pipe' }
    ],
    recommendation: 'LOW CONFIDENCE: Do NOT assume physical conduit. Likely overland street gutter runoff or blocked corridor.',
    statusNotes: 'Low-confidence candidate requiring high priority field audit'
  },
  {
    id: 'SYN-DR-016',
    name: 'Candidate Hill Flank Channel: Model Colony Far North',
    type: 'reconstructed',
    coordinates: [[18.5390, 73.8320], [18.5370, 73.8395]],
    lengthMeters: 690,
    slopePercent: 2.9,
    catchmentAreaHa: 5.5,
    diameterMm: 600,
    confidence: 'LOW',
    validationStatus: 'requires_verification',
    evidence: [
      { id: 'ev-1', label: 'Terrain flow alignment', supported: true, notes: 'Hill terrain generates high theoretical runoff' },
      { id: 'ev-2', label: 'Road corridor agreement', supported: false, notes: 'Severe misalignment with modern street layouts' },
      { id: 'ev-3', label: 'Downstream connection', supported: true, notes: 'Joins J-16' },
      { id: 'ev-4', label: 'Recent construction changes', supported: false, notes: 'Recent basement excavations may have severed natural swale' }
    ],
    recommendation: 'LOW CONFIDENCE: Ground verification needed to verify if natural drainage has been canalized or blocked by recent development.',
    statusNotes: 'Potential severed natural pathway'
  },
  {
    id: 'SYN-DR-017',
    name: 'Candidate Spur: JM Road Commercial Underpass',
    type: 'reconstructed',
    coordinates: [[18.5285, 73.8475], [18.5300, 73.8465]],
    lengthMeters: 210,
    slopePercent: 0.4,
    catchmentAreaHa: 1.8,
    diameterMm: 450,
    confidence: 'LOW',
    validationStatus: 'requires_verification',
    isProblemSegment: true,
    problemType: 'discontinuity',
    problemDescription: 'Suspected dead-end or disconnected branch leading into surcharged Junction J-08.',
    evidence: [
      { id: 'ev-1', label: 'Terrain flow alignment', supported: true, notes: 'Depression basin flow' },
      { id: 'ev-2', label: 'Road corridor agreement', supported: false, notes: 'Crosses pedestrian underpass structure' },
      { id: 'ev-3', label: 'Downstream connection', supported: true, notes: 'Feeds into J-08' },
      { id: 'ev-4', label: 'Capacity match', supported: false, notes: 'Undersized inlet for catchment' }
    ],
    recommendation: 'LOW CONFIDENCE: High likelihood of siltation and structural blockage during intense storms.',
    statusNotes: 'Potential discontinuity hotspot'
  },
  {
    id: 'SYN-DR-018',
    name: 'Candidate High-Load Link: FC-JM Interchange Zone',
    type: 'reconstructed',
    coordinates: [[18.5270, 73.8400], [18.5255, 73.8452]],
    lengthMeters: 460,
    slopePercent: 1.1,
    catchmentAreaHa: 6.2,
    diameterMm: 600,
    confidence: 'LOW',
    validationStatus: 'requires_verification',
    isProblemSegment: true,
    problemType: 'high_accumulation',
    problemDescription: 'Simulated to collect 6.2 ha urban catchment runoff into undersized 600mm candidate cross-link.',
    evidence: [
      { id: 'ev-1', label: 'Terrain flow alignment', supported: true, notes: 'Saddle depression convergence' },
      { id: 'ev-2', label: 'Road corridor agreement', supported: true, notes: 'Narrow connecting street' },
      { id: 'ev-3', label: 'Downstream connection', supported: true, notes: 'Discharges at J-07' },
      { id: 'ev-4', label: 'Hydraulic sufficiency', supported: false, notes: 'Estimated capacity insufficient for peak storm runoff' }
    ],
    recommendation: 'LOW CONFIDENCE: High surface accumulation area. Recommend hydraulic verification and physical dye tracing.',
    statusNotes: 'Candidate segment with high upstream accumulation load'
  }
];
